cabal-version: 1.24
name:          reflex-dom-test-selenium
version:       0.0.0.1
synopsis:      Testing framework for selenium tests
license:       BSD3
license-file:  LICENSE
author:        Ryan Trinkle
maintainer:    ryan.trinkle@gmail.com
stability:     Experimental
category:
    FRP, Web, GUI, HTML, Javascript, Reactive, Reactivity, User Interfaces, User-interface

build-type:    Simple

library
  default-language: Haskell98
  hs-source-dirs: src
  exposed-modules:  Reflex.Dom.Test.Selenium
  ghc-options:
      -Wall -fwarn-tabs -funbox-strict-fields -O2 -ferror-spans
      -fspecialise-aggressively
  build-depends:
    async,
    base >= 4.7 && < 4.22,
    bytestring >= 0.10 && < 0.13,
    chrome-test-utils,
    exceptions,
    hspec-core < 2.12,
    hspec-webdriver >= 1.2.2,
    http-types,
    jsaddle >= 0.9.0.0 && < 0.10,
    jsaddle-warp,
    network,
    process,
    reflex-dom-core,
    silently,
    text >= 1.2 && < 2.2,
    wai,
    warp,
    webdriver,
    websockets

  if (!os(linux) || !arch(x86_64))
    buildable: False
